name: Format

on:
  push:
    paths:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.md'
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Prettier
      run: |
        npm install --save-dev prettier

    - name: Format markdown files
      run: |
        npx prettier --write '**/*.md'

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "AutoFormat"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
